sudo: false
language: python

cache:
  directories:
    - $HOME/.cache/pip/wheels

python:
  - "2.7"
  - "3.5"

install:
  - (cd /tmp && wget https://github.com/edenhill/librdkafka/archive/0.9.1.tar.gz && tar -xzf ./0.9.1.tar.gz && cd librdkafka-0.9.1 && ./configure --prefix=$HOME/.local && make && make install)
  - pip install flake8
  - pip install --editable .

script:
  - make lint test
